name=IoTera
version=1.2.0
author=JslamA Dev
maintainer=JslamA Dev
sentence=A simple library to connect ESP8266/ESP32 devices to the IoTera mobile app.
paragraph=This library simplifies real-time communication between ESP8266/ESP32 microcontrollers and the IoTera mobile dashboard, allowing you to send sensor data and receive commands seamlessly using Firebase.
category=Communication
url=https://github.com/juslam/IoTera_Arduino
architectures=esp8266,esp32
includes=IoTeraDevice.h
depends=FirebaseClient (=1.1.8),FirebaseJson