name=IoTera
version=1.0.0
author=JslamA Dev
maintainer=JslamA Dev
sentence=Library untuk menghubungkan ESP8266/ESP32 ke aplikasi IoTera.
paragraph=Library ini mempermudah koneksi perangkat IoT ESP8266 dan ESP32 ke Firebase Realtime Database untuk berkomunikasi dengan aplikasi mobile IoTera.
category=Communication
url=https://github.com/juslam/IoTera_Arduino
architectures=esp8266,esp32
includes=IoTeraDevice.h
depends=FirebaseClient (=1.1.8),FirebaseJson
